"""Results tables whose columns are named in a header row.

Four federations in this archive publish the same fact in the same shape: a
header line that names the columns, and under it one line per competitor giving
where that competitor finished. Nothing in any of them says who beat whom, so
this adapter yields Placings and never a Bout. A podium is a real fact; the
bouts behind it are not on the page, and deriving them would be fabrication.

The four are read by one machine because they differ only in which columns are
present and what the columns are called:

  icebits   Croatian federation, 2021-2024, generated by dtournament.icebits.hr
            UZRAST  KATEGORIJA  KLUB  IME  REZULTAT
            The age class and the weight class each sit on their own line, in
            their own column, and carry down until the next one.

  izvjestaj Croatian federation, 2019, typed by hand into a Word table
            Klub  Ime i Prezime  Uzrast  Kat.KG  Osvojeno Mjesto
            Every row is self-contained: it repeats the age and weight class.

  fisav     FISav, 2008 world assaut championship, one sheet per sex
            Catégorie poids  Classement  Nom  Prénom  Nation
            The class sits on the line of its first-placed competitor and
            carries down. This is the only one of the four that names a country.

  sportu    FF Sport U, 2016 French university championship
            (rank)  class  N° licence  Nom  Prénom  Sexe  AS  Académie
            The header is reprinted above every weight class, and each row
            repeats its class, so nothing carries down at all.

WHY GEOMETRY AND NOT TEXT. A column is the meaning here: in the Croatian sheets
the difference between an age class and a weight class is *which column the word
is in* and nothing else - "Juniori" and "60-65 kg" are both a lone word on a
line. `pdftotext -layout` preserves that only by luck, and loses it whenever a
cell wraps. So each page's header row is located, its cells give the column
edges, and every word below is filed by where it sits. Layouts whose cells are
left-aligned (icebits, fisav) take bands running from each header word to the
next; layouts whose cells are centred (izvjestaj, sportu) take bands split
halfway between header cell centres, because there the content of the first
column starts well to the left of the word "Klub".

WHY RECORDS ARE NOT LINES. The 2024 Split sheet wraps long cells, so one
competitor is three visual lines - "Ana Peštaj" above, "SK STUBICA ... 1." in
the middle, "Trajkov" below - and reading line by line yields a nameless
placing and two orphans. The wrapped lines of one table row overlap vertically;
the rows of different competitors do not. So consecutive lines are grouped into
one record while their vertical extents overlap by a quarter of a line, and the
cells are joined in reading order. The threshold is measured, not assumed: in
the sheet that wraps, the overlap inside a record is 40-50% of a line; in the
sheets that do not, consecutive lines still overlap by 0.57pt of leading, which
is 5%. Grouping is asked for only by the layout that needs it, and never across
a page break, where the foot of one page sits far below the head of the next.

WHAT IS TRANSLATED AND WHAT IS NOT. The Croatian sheets state the age class in a
grammatically gendered noun - "Juniori" are male juniors, "Juniorke" female
ones, "starija_kadetkinja" an older female cadet. Reading the sex off that word
is reading the document, not guessing at it; the archive's own vocabulary is
English, so the noun is translated, and the table that does it is below where it
can be checked. The FISav sheet writes countries as three-letter French codes
(ALL is Allemagne, HON Hongrie, JAP Japon), which are likewise translated
through a table; a code not in it is kept exactly as printed and reported,
because a country guessed wrong is worse than a country left as a code.

WHAT IS REFUSED.

*No discipline is invented.* Two Croatian sheets are titled "combat i
precombat" and print the age sections twice - once for each discipline -
without saying which block is which. (Two others of the same pair label every
section "Precombat - Juniori", "Combat - Seniorke", and those labels are
kept.) The second block's categories are suffixed "(block 2)" and the
ambiguity is reported. Merging them would put two gold medals in one weight
class; naming them would be a coin toss.

*No place beyond the podium is kept.* The icebits and FISav sheets rank the
whole field - 4th, 5th, joint 5th - and schema.Placing is a podium place:
check_placing admits ranks 1, 2 and 3 and nothing else. Those rows are counted
and reported rather than dropped in silence, because the count is the size of
what the schema currently cannot hold.

*Nothing outside the competitors' table is read.* Every Croatian sheet ends with
a club medal table whose rows also begin "1.", and the university sheet ends
with a team podium. One 2019 sheet ends with exhibition bouts, given places, in
which the two fighters of a single bout stand in different weight classes -
which is what an exhibition means. Parsing stops at all of those by name, and
says so.
"""

import re

from savate import pdf
from savate.schema import MEDALS, Placing, Report, Tournament

NAME = "savate_tabular_pdf"
DESCRIPTION = ("column-headed results tables: Croatian federation reports, the "
               "FISav 2008 classement, FF Sport U (placings only)")

# ---------------------------------------------------------------- vocabulary

# Croatian age classes. Longest first: "mlađi kadet" contains "kadet", and
# "juniorke" contains "junior", so a shorter pattern tried first would swallow
# the longer one. The spellings are those the sheets actually use, including the
# underscored forms of the 2019 Word tables ("stariji_kadet").
_AGE_HR = [
    (re.compile(r"mla[dđ]\w*[\s_-]*kadet", re.I), "Younger Cadet"),
    (re.compile(r"star\w*[\s_-]*kadet", re.I), "Older Cadet"),
    (re.compile(r"kadet", re.I), "Cadet"),
    (re.compile(r"mla[dđ]\w*[\s_-]*junior", re.I), "Younger Junior"),
    (re.compile(r"star\w*[\s_-]*junior", re.I), "Older Junior"),
    (re.compile(r"junior", re.I), "Junior"),
    (re.compile(r"senior", re.I), "Senior"),
    (re.compile(r"veteran", re.I), "Veteran"),
]
# The feminine endings. Tried before the masculine ones for the same reason:
# every feminine form contains its masculine stem.
_WOMEN_HR = re.compile(r"kadetkinj|juniork|seniork|veterank|djevoj[čc]", re.I)
_MEN_HR = re.compile(r"kadet|junior|senior|veteran", re.I)

# The discipline, where a section names one. Nothing else in these sheets does.
_DISCIPLINE_HR = re.compile(r"^\s*(assaut|pre[\s-]?combat|combat)\b", re.I)

# FISav's country codes, which are abbreviations of the French names.
_FISAV_COUNTRY = {
    "FRA": "France", "SER": "Serbia", "BEL": "Belgium", "ITA": "Italy",
    "SLO": "Slovenia", "CRO": "Croatia", "RUS": "Russia", "SUI": "Switzerland",
    "FIN": "Finland", "TUR": "Turkey", "USA": "United States",
    "ALL": "Germany", "MEX": "Mexico", "AUS": "Australia", "MAR": "Morocco",
    "HON": "Hungary", "JAP": "Japan", "MAD": "Madagascar", "IRN": "Iran",
    "ALG": "Algeria", "CAN": "Canada", "GBR": "Great Britain",
    "THAI": "Thailand",
}

# Where each sheet stops being a list of competitors.
_STOP = re.compile(r"rezulatati\s+po\s+klubovima|rezultati\s+po\s+klubovima|"
                   r"najboljim\s+klubovima|natjecanju\s+je\s+sudjelovalo|"
                   r"na\s+prvenstvu\s+je\s+sudjelovalo|ekipni\s+po[bd]|"
                   r"resultats\s+savate\s+equipes", re.I)
# "Revijalni mečevi" - exhibition bouts, printed after the competition proper.
# One 2019 sheet gives them places, and the two fighters of a single exhibition
# are put in different weight classes, which is what an exhibition means: it was
# not a class anybody competed in. Recording those as cup medals would state a
# result the competition never had, so the sheet is read no further.
_EXHIBITION = re.compile(r"revijaln", re.I)
# Furniture the generated Croatian sheets print inside the table's own columns.
_NOISE = re.compile(r"dtournament\.icebits\.hr|about:blank|^natjecanje\b|"
                    r"rezulatati\s+po\s+kategorijama|^\d+\s*/\s*\d+$|"
                    r"^delegat$|^ukupni$", re.I)
# "Eliminacijske mečeve nisu prošli" - competitors who did not come through
# the eliminations. They are entrants, not placings, and the sheet gives them
# no class and no place.
_ELIMINATED = re.compile(r"eliminacijske\s+me[čc]eve", re.I)

_RANK = re.compile(r"^\s*(\d{1,2})\s*\.?\s*(?:mjesto)?\s*\.?\s*$", re.I)
# A weight class in any of the forms the Croatian and FISav sheets use:
# "-48 kg", "48-52 kg", "+85 kg", "85+kg", "25-30", "75+". The university
# sheet writes its class inside the rank cell and parses it separately.
_WEIGHT = re.compile(
    r"^(?:(?P<lo>\d{2,3})\s*[-–—]\s*(?P<hi>\d{2,3})"
    r"|(?P<sign>[-+−])\s*(?P<one>\d{2,3})"
    r"|(?P<one2>\d{2,3})\s*(?P<plus>\+))\s*(?:kgs?)?\s*$", re.I)


def _weight(text):
    """(kilos, bound) for a printed weight class, or None.

    A band - "48-52", "25-30" - is the class's own upper limit written as the
    gap between it and the class below, so the class is the upper number. That
    reading is the archive's, in podium_pdf, and these sheets corroborate it:
    the Croatian ladders run 25-30, 30-35, 35-40 with no overlap and no gap.
    """
    found = _WEIGHT.match(" ".join(str(text or "").split()))
    if not found:
        return None
    if found.group("hi"):
        return found.group("hi"), "under"
    if found.group("one"):
        sign = found.group("sign")
        return found.group("one"), ("over" if sign == "+" else "under")
    return found.group("one2"), "over"


def _weight_label(kilos, bound):
    return f"{'+' if bound == 'over' else '-'}{kilos} kg"


def _age_hr(text):
    for pattern, age in _AGE_HR:
        if pattern.search(text or ""):
            return age
    return ""


def _gender_hr(text):
    text = text or ""
    if _WOMEN_HR.search(text):
        return "Women"
    if _MEN_HR.search(text):
        return "Men"
    return ""


def _label(parts):
    return " ".join(p for p in parts if p)


# ------------------------------------------------------------------ geometry

# The word that opens each column, in order, for each sheet. Naming them is
# what makes the header readable: the FISav header sets "Catégorie poids" and
# "Classement" two points apart while "Ime i Prezime" keeps its own words two
# points apart too, so no gap width tells a column break from a word break. The
# names do, and these headers are fixed text.
_COLUMNS = {
    "icebits": ([r"^UZRAST$", r"^KATEGORIJA$", r"^KLUB$", r"^IME$",
                 r"^REZULTAT$"], False, False),
    "izvjestaj": ([r"^KLUB$", r"^IME$", r"^UZRAST$", r"^KAT", r"^OSVOJENO$"],
                  True, False),
    "fisav": ([r"^CAT[EÉ]GORIE$", r"^CLASSEMENT$", r"^NOM$", r"^PR[EÉ]NOM$",
               r"^NATION$"], False, False),
    # The rank column carries no header at all and the class is its own header,
    # so the sportu header's first cell is whatever stands left of "N°".
    "sportu": ([r"^N°?$", r"^NOM$", r"^PR[EÉ]NOM$", r"^SEXE$", r"^AS$",
                r"^ACAD[EÉ]MIE$"], True, True),
}


def _cells_of(header, kind):
    """(column names, column edges) for a header line, or (None, None).

    Each sheet says how its content sits under the header. Left-aligned columns
    (icebits, FISav) start exactly where their header word starts, so a band
    runs from one header cell to the next. Centred columns (the two Word-built
    sheets) have content spilling to both sides of the header word, so the band
    boundary is halfway between one cell's centre and the next's.
    """
    patterns, centred, leading = _COLUMNS[kind]
    words = sorted(header, key=lambda w: w.x0)
    starts, at = [], 0
    for pattern in patterns:
        found = next((i for i in range(at, len(words))
                      if re.match(pattern, words[i].text, re.I)), None)
        if found is None:
            return None, None
        starts.append(found)
        at = found + 1
    if leading:
        if not starts[0]:
            return None, None
        starts.insert(0, 0)
    groups = [words[starts[i]:starts[i + 1] if i + 1 < len(starts) else None]
              for i in range(len(starts))]
    if centred:
        centres = [(g[0].x0 + g[-1].x1) / 2 for g in groups]
        edges = [-1e6] + [(centres[i] + centres[i + 1]) / 2
                          for i in range(len(centres) - 1)] + [1e6]
    else:
        # A hair of slack: a cell's first glyph occasionally starts a fraction
        # of a point left of the header word above it.
        edges = [g[0].x0 - 2 for g in groups] + [1e6]
        edges[0] = -1e6
    return [pdf.text_of(g) for g in groups], edges


def _split(words, edges):
    """The text of each column, for one group of words."""
    cells = [[] for _ in range(len(edges) - 1)]
    for word in sorted(words, key=lambda w: (w.top, w.x0)):
        for i in range(len(edges) - 1):
            if edges[i] <= word.middle < edges[i + 1]:
                cells[i].append(word.text)
                break
    return [" ".join(c).strip() for c in cells]


def _extent(line):
    return min(w.top for w in line), max(w.bottom for w in line)


# How much two lines must overlap before they are one wrapped table row. A
# generous margin either way: in the sheet that wraps, the overlap inside a row
# is 40-50% of a line's height; in the sheets that do not, consecutive lines
# still overlap by 0.57pt of leading, which is under 5%.
_WRAPPED = 0.25


def _records(lines, wrapped=False):
    """Group consecutive lines into table rows.

    Yields [words]. Only the sheets that wrap long cells ask for grouping: in
    those, a wrapped cell puts part of its row on a line of its own, well
    overlapping the row's other lines, while separate rows never do. Asking for
    it where it is not needed would weld a whole page into one row, since even
    single-spaced text lines overlap slightly. Pages are kept apart for the
    same reason: the foot of one page sits far below the head of the next, so
    an overlap test that ignored the page number would join every page in the
    document into a single record.
    """
    if not wrapped:
        return [list(line) for line in lines]
    out = []
    for line in lines:
        top, bottom = _extent(line)
        if out and out[-1][0][0].page == line[0].page:
            previous_top, previous_bottom = out[-1][1], out[-1][2]
            overlap = previous_bottom - top
            shorter = min(bottom - top, previous_bottom - previous_top) or 1
            if overlap / shorter >= _WRAPPED:
                out[-1][0].extend(line)
                out[-1][2] = max(previous_bottom, bottom)
                continue
        out.append([list(line), top, bottom])
    return [group for group, _top, _bottom in out]


# ------------------------------------------------------------------- layouts

def _header_kind(text):
    """Which of the four sheets a header line belongs to, or ""."""
    upper = text.upper()
    if "UZRAST" in upper and "KATEGORIJA" in upper and "REZULTAT" in upper:
        return "icebits"
    if "KLUB" in upper and "UZRAST" in upper and "MJESTO" in upper:
        return "izvjestaj"
    if "CLASSEMENT" in upper and "NOM" in upper:
        return "fisav"
    if "LICENCE" in upper and "NOM" in upper and "SEXE" in upper:
        return "sportu"
    return ""


def _emit(placings, slug, klass, rank, fighter, report, country="", club=""):
    """Add one placing, or say why it was not added."""
    if not fighter:
        report.problem(f"{klass['category']}: a {MEDALS.get(rank, rank)} "
                       f"with no name")
        return
    placings.append(Placing(
        tournament=slug,
        placing_id=f"{slug}-{len(placings) + 1:04d}",
        rank=rank, medal=MEDALS[rank],
        fighter=fighter, country=country, club=club,
        result_source="reported",
        **klass,
    ))


class _Sections:
    """Age sections in document order, so a re-opened one can be told apart.

    The combat-and-precombat sheets print "Juniori" twice, once per discipline,
    and label neither. Two blocks under one label would mean two golds in one
    weight class, so the later block's categories carry a "(block N)" suffix and
    the reason is reported. The suffix says the document distinguished them; it
    does not say what the distinction was.
    """

    def __init__(self):
        self.order = []
        self.repeats = []

    def open(self, key):
        if key in self.order and self.order[-1] != key:
            block = self.order.count(key) + 1
            self.order.append(key)
            self.repeats.append(key)
            return f" (block {block})"
        self.order.append(key)
        return ""


def _read_icebits(lines, slug, report):
    placings, problems = [], 0
    edges = None
    section = {"age": "", "gender": "", "discipline": "", "suffix": ""}
    pending_section = ""
    klass = None
    sections = _Sections()
    beyond_podium = 0

    def settle():
        """Turn the accumulated UZRAST text into the current section."""
        nonlocal pending_section, klass
        if not pending_section:
            return
        text = pending_section
        pending_section = ""
        discipline = ""
        found = _DISCIPLINE_HR.match(text)
        if found:
            discipline = re.sub(r"\s+", "", found.group(1)).title()
        age, gender = _age_hr(text), _gender_hr(text)
        if not age or not gender:
            report.problem(f"age section {text!r} is not one this adapter "
                           f"knows how to read")
        suffix = sections.open((discipline, age, gender))
        section.update(age=age, gender=gender, discipline=discipline,
                       suffix=suffix)
        klass = None

    for group in _records(lines, wrapped=True):
        text = pdf.text_of(sorted(group, key=lambda w: w.x0))
        if _STOP.search(text):
            break
        kind = _header_kind(text)
        if kind == "icebits":
            _names, edges = _cells_of(group, "icebits")
            continue
        if edges is None or _NOISE.search(text.strip()):
            continue
        cells = _split(group, edges)
        if len(cells) < 5:
            continue
        uzrast, kategorija, klub, ime, rezultat = cells[:5]
        if uzrast and not (kategorija or klub or ime or rezultat):
            # Wrapped section labels ("Precombat -" / "Juniorke") arrive as two
            # lines that do not overlap, so they are joined here rather than by
            # geometry. Only while the text so far is plainly unfinished.
            if pending_section and (pending_section.rstrip().endswith("-")
                                    or not _age_hr(pending_section)):
                pending_section += " " + uzrast
            else:
                settle()
                pending_section = uzrast
            continue
        settle()
        if kategorija and not (klub or ime or rezultat):
            weight = _weight(kategorija)
            if not weight:
                report.problem(f"weight class {kategorija!r} is not one this "
                               f"adapter knows how to read")
                klass = None
                continue
            kilos, bound = weight
            klass = {
                "category": _label([section["discipline"], section["age"],
                                    section["gender"],
                                    _weight_label(kilos, bound)])
                           + section["suffix"],
                "gender": section["gender"], "age_class": section["age"],
                "weight_kg": kilos, "weight_bound": bound,
            }
            continue
        if not (ime or klub or rezultat):
            continue
        if klass is None:
            problems += 1
            continue
        found = _RANK.match(rezultat)
        if not found:
            report.problem(f"{klass['category']}: {ime or klub!r} has no place "
                           f"printed against it")
            continue
        rank = str(int(found.group(1)))
        if rank not in MEDALS:
            beyond_podium += 1
            continue
        # No country. These sheets name a club, never a nationality, and the
        # host federation's own is not the fighter's: the 2019 Vukovar sheet
        # has a Hungarian club in it, and stamping "Croatia" on Farkas Botond
        # because the tournament was Croatian is exactly the invention the
        # archive forbids.
        _emit(placings, slug, klass, rank, ime, report, club=klub)

    if problems:
        report.problem(f"{problems} row(s) stood before any weight class and "
                       f"were skipped")
    return placings, beyond_podium, sections.repeats


def _read_izvjestaj(lines, slug, report):
    placings = []
    edges = None
    beyond_podium = 0
    unplaced = 0

    for group in _records(lines):
        text = pdf.text_of(sorted(group, key=lambda w: w.x0))
        if _STOP.search(text):
            break
        if _EXHIBITION.search(text):
            report.problem("the sheet ends with exhibition bouts ('revijalni "
                           "mečevi'), which are not places in the competition "
                           "and are not read")
            break
        if _header_kind(text) == "izvjestaj":
            _names, edges = _cells_of(group, "izvjestaj")
            continue
        if edges is None or _ELIMINATED.search(text):
            continue
        cells = _split(group, edges)
        if len(cells) < 5:
            continue
        klub, ime, uzrast, kat, mjesto = cells[:5]
        if not (ime and uzrast and kat):
            # Entrants beaten in the eliminations are printed with the name and
            # club alone. They finished nowhere the sheet states, so there is
            # no placing to make.
            if ime and not mjesto:
                unplaced += 1
            continue
        found = _RANK.match(mjesto)
        if not found:
            unplaced += 1
            continue
        weight = _weight(kat)
        if not weight:
            report.problem(f"weight class {kat!r} is not one this adapter "
                           f"knows how to read")
            continue
        kilos, bound = weight
        age, gender = _age_hr(uzrast), _gender_hr(uzrast)
        if not age or not gender:
            report.problem(f"age class {uzrast!r} is not one this adapter "
                           f"knows how to read")
        rank = str(int(found.group(1)))
        if rank not in MEDALS:
            beyond_podium += 1
            continue
        klass = {
            "category": _label([age, gender, _weight_label(kilos, bound)]),
            "gender": gender, "age_class": age,
            "weight_kg": kilos, "weight_bound": bound,
        }
        # No country. These sheets name a club, never a nationality, and the
        # host federation's own is not the fighter's: the 2019 Vukovar sheet
        # has a Hungarian club in it, and stamping "Croatia" on Farkas Botond
        # because the tournament was Croatian is exactly the invention the
        # archive forbids.
        _emit(placings, slug, klass, rank, ime, report, club=klub)

    if unplaced:
        report.problem(f"{unplaced} competitor(s) are listed with no place - "
                       f"beaten in the eliminations, or the cell was left "
                       f"blank - and are not recorded as placings")
    return placings, beyond_podium


_FISAV_CLASS = re.compile(r"^\s*([HF])\s*:?\s*(.*)$")


def _read_fisav(lines, slug, meta, report):
    placings, edges, klass = [], None, None
    beyond_podium = 0
    codes = set()

    for group in _records(lines):
        text = pdf.text_of(sorted(group, key=lambda w: w.x0))
        if _header_kind(text) == "fisav":
            _names, edges = _cells_of(group, "fisav")
            continue
        if edges is None:
            continue
        cells = _split(group, edges)
        if len(cells) < 5:
            continue
        poids, place, nom, prenom, nation = cells[:5]
        if poids:
            found = _FISAV_CLASS.match(poids)
            weight = _weight(found.group(2)) if found else None
            if not found or not weight:
                # The second header line ("Weight class Position Surname Name")
                # lands here and is not a class; so would anything else odd.
                if not _RANK.match(place or ""):
                    continue
                report.problem(f"weight class {poids!r} is not one this "
                               f"adapter knows how to read")
                klass = None
                continue
            kilos, bound = weight
            gender = "Men" if found.group(1).upper() == "H" else "Women"
            age = meta.get("age_class", "")
            klass = {
                "category": _label([age, gender, _weight_label(kilos, bound)]),
                "gender": gender, "age_class": age,
                "weight_kg": kilos, "weight_bound": bound,
            }
        found = _RANK.match(place or "")
        if not found:
            continue
        if klass is None:
            report.problem(f"{nom!r} is placed before any weight class")
            continue
        rank = str(int(found.group(1)))
        if rank not in MEDALS:
            beyond_podium += 1
            continue
        code = (nation or "").strip().upper()
        if code and code not in _FISAV_COUNTRY:
            report.problem(f"country code {code!r} is not in this adapter's "
                           f"table and is kept as printed")
        if code:
            codes.add(code)
        _emit(placings, slug, klass, rank,
              " ".join(x for x in (nom, prenom) if x).strip(), report,
              country=_FISAV_COUNTRY.get(code, nation.strip()))

    return placings, beyond_podium, sorted(codes)


_SPORTU_CLASS = re.compile(
    r"^\s*(?P<rank>\d{1,2})?\s*(?P<sign>[-+])?(?P<kg>\d{2,3})\s*KG\b", re.I)


def _read_sportu(lines, slug, meta, report):
    placings, edges = [], None
    beyond_podium = 0

    for group in _records(lines):
        text = pdf.text_of(sorted(group, key=lambda w: w.x0))
        if _STOP.search(text):
            break
        if _header_kind(text) == "sportu":
            _names, edges = _cells_of(group, "sportu")
            continue
        if edges is None:
            continue
        cells = _split(group, edges)
        if len(cells) < 7:
            continue
        # The rank column carries no header, so it shares a band with the
        # class and is split off it by pattern below.
        head, _licence, nom, prenom, sexe, club = cells[:6]
        found = _SPORTU_CLASS.match(head)
        if not found or not found.group("rank"):
            continue
        gender = ("Women" if (sexe or "").strip().upper() == "F"
                  else "Men" if (sexe or "").strip().upper() in ("H", "M")
                  else "")
        if not gender:
            report.problem(f"row {head!r} does not state a sex")
        bound = "over" if found.group("sign") == "+" else "under"
        kilos = found.group("kg")
        age = meta.get("age_class", "")
        klass = {
            "category": _label([age, gender, _weight_label(kilos, bound)]),
            "gender": gender, "age_class": age,
            "weight_kg": kilos, "weight_bound": bound,
        }
        rank = str(int(found.group("rank")))
        if rank not in MEDALS:
            beyond_podium += 1
            continue
        # The sheet gives an académie, not a country: every competitor is at a
        # French university, which is not the same fact as their nationality.
        _emit(placings, slug, klass, rank,
              " ".join(x for x in (nom, prenom) if x).strip(), report,
              club=club)

    return placings, beyond_podium


# ---------------------------------------------------------------------- read

def _brief(error):
    """One line of an exception. poppler answers a non-PDF with hundreds."""
    text = " ".join(str(error).split())
    return text if len(text) <= 160 else text[:157] + "..."


def read(source, slug, meta=None, **options):
    """(Tournament, [Placing], Report) from one column-headed results table."""
    from savate import sources

    meta = meta or {}
    report = Report(source=str(source), adapter=NAME)
    tournament = Tournament(
        slug=slug, name=meta.get("name", slug),
        discipline=meta.get("discipline", ""), level=meta.get("level", ""),
        format=meta.get("format", ""), age_class=meta.get("age_class", ""),
        year=meta.get("year", ""), city=meta.get("city", ""),
        country=meta.get("country", ""),
        source=str(source), adapter=NAME)

    try:
        path = sources.fetch_archived(str(source)) if options.get("archived") \
            else sources.fetch(source, refresh=options.get("refresh", False))
    except Exception as e:
        report.problem(f"the document could not be fetched: {_brief(e)}")
        return tournament, [], report

    try:
        words = pdf.words(path)
    except Exception as e:
        report.problem(f"the document could not be read as a PDF: {_brief(e)}")
        return tournament, [], report

    report.read = len({w.page for w in words})
    lines = pdf.rows(words)
    kinds = [k for k in (_header_kind(pdf.text_of(l)) for l in lines) if k]
    if not kinds:
        report.problem("no column header this adapter recognises - the sheet "
                       "is not one of the four it reads")
        return tournament, [], report
    kind = kinds[0]
    report.notes["layout"] = kind

    beyond_podium, repeats, codes = 0, [], []
    try:
        if kind == "icebits":
            placings, beyond_podium, repeats = _read_icebits(
                lines, slug, report)
        elif kind == "izvjestaj":
            placings, beyond_podium = _read_izvjestaj(lines, slug, report)
        elif kind == "fisav":
            placings, beyond_podium, codes = _read_fisav(
                lines, slug, meta, report)
        else:
            placings, beyond_podium = _read_sportu(lines, slug, meta, report)
    except Exception as e:
        # A malformed sheet is a report, not a traceback. Whatever was read
        # before the failure is lost rather than half-kept, because a partial
        # table cannot be told from a complete one after the fact.
        report.problem(f"the {kind} table could not be read: "
                       f"{type(e).__name__}: {_brief(e)}")
        return tournament, [], report

    report.notes["placings"] = len(placings)
    if beyond_podium:
        report.notes["beyond_podium"] = beyond_podium
        report.problem(
            f"{beyond_podium} competitor(s) are placed 4th or lower on this "
            f"sheet and are not kept: schema.Placing is a podium place and "
            f"check_placing admits ranks 1-3 only")
    if repeats:
        report.notes["repeated_sections"] = [" ".join(k).strip()
                                             for k in repeats]
        report.problem(
            "age section(s) " +
            ", ".join(sorted({" ".join(k).strip() for k in repeats})) +
            " are opened twice in one document - these sheets cover two "
            "disciplines and label neither block - so the later block's "
            "categories are suffixed '(block N)'")
    if codes:
        report.notes["country_codes"] = codes
    if not placings:
        report.problem(f"the {kind} header was found but no placing was read "
                       f"under it")
    return tournament, placings, report
